### ISSUE TITLE
Add optional model argument

### ISSUE THREAD

**Issue by edgrosvenor** [christophrumpel/laravel-factories-reloaded#11]
I have a project with dozens of models. Selecting them from a list would be cumbersome. Would you be open to accepting a PR that adds an optional argument to which one would pass the model and, if provided, would skip the selection menu and just create the factory? I'd be happy to add this to the command and update the docs to reflect the change.

**Comment by christophrumpel** [comment]
Hey, yeah sure. I would be open for that 👍
