### ISSUE TITLE
Publish Config

### ISSUE THREAD

**Issue by kenwilliams5** [christophrumpel/laravel-factories-reloaded#14]
Can you document how to publish the config? I have my models in a Models directory and can't figure out how to change the config so factories-reloaded can find them.

**Comment by christophrumpel** [comment]
Thanks for mentioning. I just noticed there is a bug I need to fix.

**Comment by christophrumpel** [comment]
I just published a new realease 0.0.9 where I fixed this and added it to the readme. You can now publish the config like this:

`php artisan vendor:publish --provider="Christophrumpel\LaravelFactoriesReloaded\LaravelFactoriesReloadedServiceProvider"
`

Let me know if it works for you as well.

**Comment by kenwilliams5** [comment]
Works perfect!! Thanks for the quick fix!

**Comment by christophrumpel** [comment]
Great 👍
