### ISSUE TITLE
No models in list

### ISSUE THREAD

**Issue by kode-on-kanvas** [christophrumpel/laravel-factories-reloaded#15]
I have a brand new laravel installation with two models and a weird behavior. When I call `php artisan make:factory-reloaded` I get the following output

```
 Please pick a model:
  [0] 
```

with a blinking prompt next to the [0] and no chance to interact. I have to shut down the terminal. 
Any ideas?

**Comment by christophrumpel** [comment]
Hey, that's weird. Tried it on my site with a new laravel installation without a problem. Which Laravel version are you using? Which PHP version? and which package version?

**Comment by Artessan** [comment]
Hey @kode-on-kanvas are you using windows? if this is the case the error is not relate to the package, is just the win terminal that dont support the selection step. You can try publish the assets and see the error is the same.

**Comment by christophrumpel** [comment]
Let me know if you have more info on that, in the meantime, I will close the issue.
