### ISSUE TITLE
Some options for states???

### ISSUE THREAD

**Issue by Artessan** [christophrumpel/laravel-factories-reloaded#21]
Hey @christophrumpel thanks for a good package. 

I want to know your opinion on how to handle the states in the factories, for now I and trying with
- one class for each state (which can be many classes for some models)
- overwriting the attribute (each time that a no default state is needed is necessary to overwrite)

I'm thinking is something like an apply method that accept a state string and mutate the data.

**Comment by christophrumpel** [comment]
Hey.

good point. I need to add that to the docs.

So I would use methods to define `states` like here to define a `published` recipe:

```php
<?php

namespace Tests\Factories;

use App\Recipe;
use Christophrumpel\LaravelFactoriesReloaded\BaseFactory;
use Faker\Generator;

class RecipeFactory extends BaseFactory
{

    protected string $modelClass = Recipe::class;

    /**
     * @var bool
     */
    private bool $isPublished = false;

    public function create(array $extra = []): Recipe
    {
        return parent::build($extra);
    }

    public function make(array $extra = []): Recipe
    {
        return parent::build($extra, 'make');
    }

    public function getData(Generator $faker): array
    {
        return [
            'category_id' => 1,
            'name' => $faker->name,
            'is_published' => $this->isPublished,
        ];
    }

    public function published(): self
    {
        $this->isPublished = true;

        return $this;
    }

}

```

Then you can use it like:

```php
RecipeFactory::new()
->published()
->create();
```

I think in some cases your idea with different factory classes for states makes also sense, but mostly I would do it through properties like here. Does this help?

**Comment by christophrumpel** [comment]
Does this solve your answer @Artessan ?

**Comment by Artessan** [comment]
Hey, thanks for the answer and sorry for the long delay in the response, you definitely add some lights. I tried  this and is a good option  for now my unique concern is with some models with many field to change based many states, a have to use the properties as arrays to contain the data for each state in that way a have less properties. 

Thanks again is a good option.

**Comment by christophrumpel** [comment]
No worries. Do you want to share your example and show what is better with the current default solution? I could take a look and see if my package could help with somehow.
