### ISSUE TITLE
Bug: locale from app.faker_locale not loaded

### ISSUE THREAD

**Issue by ziming** [christophrumpel/laravel-factories-reloaded#22]
In the default factories from Laravel.

I can specify my faker_locale in config/app.php to be something like

```php
'faker_locale' => 'en_SG',
```

And I get to do:

```php
'mobile_phone' => $faker->unique()->mobileNumber,
```

However in your Factory classes, I will just get the following error:

```
InvalidArgumentException with message 'Unknown formatter "mobileNumber"'
```

I need to do this in the getData method for it to work.

```php
public function getData(Generator $faker): array
    {
        $faker->addProvider(new \Faker\Provider\en_SG\PhoneNumber($faker));

        return [
            'mobile_phone' => $faker->unique()->mobileNumber,
            // other items.
        ];
    }
```

It will be good if you auto add the locale we chose in `config('app.faker_locale')` like what default Laravel does. 

Thank you

**Comment by christophrumpel** [comment]
Thanks. That's interesting. I will it a look now.

**Comment by christophrumpel** [comment]
Hey @ziming,  just pushed a new release v0.0.14 with the bugfix. Can you update and try again?

**Comment by ziming** [comment]
Looks like it works now. Thank you :)

**Comment by christophrumpel** [comment]
Perfect. Thanks for testing and I learned something new too :-)
