### ISSUE TITLE
Getting this exception when I run composer update

### ISSUE THREAD

**Issue by ziming** [christophrumpel/laravel-factories-reloaded#23]
```
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan ide-helper:generate
Exception: get_class() expects parameter 1 to be object, null given
Skipping \Christophrumpel\LaravelCommandFilePicker\LaravelCommandFilePickerFacade.
```

**Comment by christophrumpel** [comment]
Hey, ok that's strange. What are you upgrading exactly? My package? From which version?

**Comment by ziming** [comment]
I think from the error message,  \Christophrumpel\LaravelCommandFilePicker\LaravelCommandFilePickerFacade causes an error with 

https://github.com/barryvdh/laravel-ide-helper

When php aristan ide-helper:generate command is run

**Comment by christophrumpel** [comment]
ah I see. got an idea. Going to check it later today. Thanks for mentioning!

**Comment by christophrumpel** [comment]
I just pushed a new release. Can you try the new version again?

**Comment by ziming** [comment]
It works now but strange that i had to change "christophrumpel/laravel-factories-reloaded": "^0.0.14", to "christophrumpel/laravel-factories-reloaded": "^0.0.15" in composer.json then run composer update for it to update to the new version. Just composer update didn't update it.

But you can close this issue now. Thank you :)

**Comment by christophrumpel** [comment]
Hmm not sure either. Maybe the specified version was too specific?

Thanks for testing!
