### ISSUE TITLE
overwriteDefaults only apply last one

### ISSUE THREAD

**Issue by irakan** [christophrumpel/laravel-factories-reloaded#41]
So If I have:

UserFactory::new()
    ->active()
    ->admin()
    ->create();

```
public function active()
{
    return tap(clone $this)->overwriteDefaults([
        'active' => true,
    ]);
}
public function admin()
{
    return tap(clone $this)->overwriteDefaults([
        'admin' => true,
    ]);
}
```

It will only apply the last method that has `overwriteDefaults` which is  `->admin()` and ignore `->active()`  overwriteDefaults.

**Comment by christophrumpel** [comment]
Thanks @irakan, somehow this case what not tested. I just pushed a fix and roll out a new release 👍

**Comment by christophrumpel** [comment]
New release 1.0.4 available now with a fix.
