### ISSUE TITLE
Support for factory callbacks

### ISSUE THREAD

**Issue by JoshMoreno** [christophrumpel/laravel-factories-reloaded#42]
Hey @christophrumpel 
Really liking the package. Found it after reading the stitcher post. 
Any plans to support [factory callbacks](https://github.com/christophrumpel/laravel-factories-reloaded/issues/new)?

P.S. I'm working on a PR for generating default attributes if we're not migrating an existing factory. Basically what [this package](https://github.com/mpociot/laravel-test-factory-helper) does, but with class based factories.

**Comment by christophrumpel** [comment]
Hey, thanks man.

I haven't thought about callbacks yet. Probably because they are not too complicated to add to a class based factory. But it might make sense to make this easier right? What do you use it for?

Oh the PR looks nice. So that default values get generated based on a migration, right? Sounds cool. let me know if you need anything.

**Comment by JoshMoreno** [comment]
Ahh, you're right, it's not that complicated. I forgot about the section dedicated to callbacks in the article - https://stitcher.io/blog/laravel-beyond-crud-09-test-factories#factories-in-factories

For nearly all projects I use them for adding user roles to users. So create the user, then assign them a role.

It's actually way easier than I was thinking. The following should do the trick.

```
protected array $roles = [];

    public function create(array $extra = []): User
    {
        $user = parent::build($extra);

        foreach($this->roles as $role) {
            $user->assignRole($role);
        }

        return $user;
    }

    public function roles(...$roles)
    {
        $this->roles = $roles;
    }
```

Think it would be useful to include in the docs? I'm thinking yes so it's on par with the laravel docs.

**Comment by christophrumpel** [comment]
Hey, ah yeah got it.

Personally, I would still use a method to add roles so it is more obvious and not hidden, but that might be a personal thing. I will try to enhance the docs for that 👍
