### ISSUE TITLE
->times() breaks most functionality added to factory

### ISSUE THREAD

**Issue by JoshMoreno** [christophrumpel/laravel-factories-reloaded#44]
```
UserFactory::new()
    ->with(\App\Review::class, 'reviews', 10)
    ->times(10)
    ->create();
```

**Expected**
10 users with 10 reviews each

**Actual**
10 users with 0 reviews

It looks like `->times()` is just getting the attribute data and creating models from that, but the factories might have additional methods, properties, and logic in the create/make methods. Might be able to fix this and simplify the code by cloning the factory X times, passing it to `CollectionFactory`, and then calling create/make on each clone individually. Any thoughts or concerns before I work on a PR in the next few days?

**Comment by christophrumpel** [comment]
Oh thanks, this somehow slipped through the tests. Will check out your PR 👍
