### ISSUE TITLE
Support closures

### ISSUE THREAD

**Issue by irakan** [christophrumpel/laravel-factories-reloaded#48]
```php
public function getDefaults(Faker $faker): array
{
    return [
        'name' => $faker->name,
        'country_id' => CountryFactory::new(), // this will still be created in database even if I overwrite it
    ];
}
```
```php
public function country(Country $country)
{
    return tap(clone $this)->overwriteDefaults([
        'country_id' => $country->id,
    ]);
}
```

If I used the `country` method, it will actually overwrite the `country_id` value but it will still create a `Country` instance that was already in the defaults and save it in database.
```
UserFactory::new()->country($country)->create();
dd(count(Country::all())); // 2
```
Before, when I was using the default laravel factories I used [closures to solve this issue](https://laracasts.com/discuss/channels/testing/overriding-values-in-model-factories?page=1#reply=326322):

```php
return [
    'name' => $faker->name,
    'country_id' => function () {
        return factory(Country::class)->create()->id;
    },
];
```

**Comment by christophrumpel** [comment]
Hey, sry I somehow didn't see this issue. So what is your main goal? You want to set the foreign key "country_id" in the defaults method, but also provide a  "country" method to override the id if given? Ah I see and if set, it shouldn't be created as a DB entry.

I think this issue will be solved with the changes from this PR: #50 
Let's try again when this is merged.

**Comment by christophrumpel** [comment]
Can you try again now with the new version `v1.0.8`?

**Comment by irakan** [comment]
Yes, `v1.0.8` did it solve it. 

Closing this since its solved..thank you.

**Comment by christophrumpel** [comment]
Perfect, thanks for letting me know 👍
