### ISSUE TITLE
Hardcoded `id` when using factory as data

### ISSUE THREAD

**Issue by GuidoHendriks** [christophrumpel/laravel-factories-reloaded#54]
In here we reference hardcoded to `id` when using a factory as a data. Would you say it's better if we use `getKeyName()` (or something similar) here? Could do the work, let me know what you think. 👍 

https://github.com/christophrumpel/laravel-factories-reloaded/blob/aea2253f5d3af904dbfb8755de32df78c90e0c72/src/TranslatesFactoryData.php#L19

**Comment by nuernbergerA** [comment]
Good catch 👍

**Comment by christophrumpel** [comment]
Yeah good catch @GuidoHendriks , a PR with a test would be great.

**Comment by GuidoHendriks** [comment]
Will create one tomorrow. 👍

**Comment by GuidoHendriks** [comment]
I'm currently implementing this. The implementation is really easy, literally just replacing `id` with `getKey()`. The tests are a bit more complicated tho.

If I reproduce my own use case I will need a model and factory that has a custom key. Could create new ones or modify existing ones. But is that the right way forward? We might end up with a lot of different models and factories for specific use cases, likely to become cluttered.

Any thoughts?

**Comment by christophrumpel** [comment]
yeah you are right. The setup for the tests is already quite heavy. I'm fine with the PR without the test and I will give it another thought if I still want to add it.
