### ISSUE TITLE
Using model in data like in Laravel factories

### ISSUE THREAD

**Issue by GuidoHendriks** [christophrumpel/laravel-factories-reloaded#59]
In Laravel factories you can do this:

```php
$user = User::first();

factory(Group::class)->create([
    'user_id' => $user,
]);
```

I would suggest adding this here as well. This would make my life easier at least, as I'm using stuff like this pretty often:

```php
TeamFactory::new()->create([
    'user_id' => UserFactory::new()->create([
        'name' => 'Foo bar',
    ]),
]);
```

Which doesn't work so I have to do this what is pretty ugly:

```php
TeamFactory::new()->create([
    'user_id' => UserFactory::new()->create([
        'name' => 'Foo bar',
    ])->id,
]);
```

I could do the work, just wanted to know what you think about it before I do.

**Comment by christophrumpel** [comment]
Hey, so we currently support factory classes for a relation key field like:

```php
$recipe = RecipeFactory::new()
            ->create([
                'group_id' => GroupFactory::new(),
            ]);
```

Here we are checking for this and returning the `key` of the model then:
https://github.com/christophrumpel/laravel-factories-reloaded/blob/master/src/TranslatesFactoryData.php#L30-L32

I don't find myself often using a given model in a test, but I can see how this can be helpful. So I think we could easily check for a model instance as well there. A PR with a test would be nice if you could do that.

Regarding this example:

```php
TeamFactory::new()->create([
    'user_id' => UserFactory::new()->create([
        'name' => 'Foo bar',
    ]),
]);
```

We are currently discussing about a solution to make it easier to create a model with a related model where you also want to call custom methods. You can read about it here: #58 

With this addition it would be possible to achieve your example like this:

```php
GroupFactory::new()
    ->with(RecipeFactory::new()->customMethod())
    ->create();
```

Inside the custom method you can for example override any data.

**Comment by GuidoHendriks** [comment]
I’m currently in the progress of a big overhaul of my project, which causes me to swap a lot of Laravel factories with reloaded ones. In most cases it’s just replacing `factory(Something::class)` with `SomethingFactory::new()`.

So having the same behavior as Laravel factories really helps. Second example is no different than first as factory returns a model there as well. So should be perfect. 

Expect a PR with tests soon. 👍🏻
