### ISSUE TITLE
Mass Assignment

### ISSUE THREAD

**Issue by YannickYayo** [christophrumpel/laravel-factories-reloaded#61]
Hi,

On Laravel's factories, Mass assignment protection is automatically disabled when creating models on our tests ([https://laravel.com/docs/7.x/database-testing](url)).

It seems like it's not the case with this package, on my model i have columns on the `$guarded` protected property, and i can't set them with :

``` php
CompanyFactory::new()->create([
    'name' => 'Yannick',
]);
```

Here the name will not be "Yannick" but the default value set on the Factory itself.

**Comment by christophrumpel** [comment]
Hey,

there is an option in the config to `unguard` all storing: `'unguard_models' => false,`

Just set it to true and let me know if it works for you then. greets

**Comment by YannickYayo** [comment]
Oh yest it works !

My bad I didn't pay enough attention to the config file. Thank you :D

**Comment by christophrumpel** [comment]
No worries. Glad it works now 👍
