### ISSUE TITLE
Deep nested relationships don't get persisted

### ISSUE THREAD

**Issue by simonschaufi** [christophrumpel/laravel-factories-reloaded#73]
Hi, I have quite a deep tree of objects I want to test and realized that only the outer object with ONE level deeper gets persisted but from the 2nd level on the objects are only relations to the parent object but are NOT in the database.

My code looks like this:

```php
$root = FactoryA::new()
    ->withFactory(
        FactoryB::new()
            ->withFactory(
                FactoryC::new()
                    ->withFactory(
                        FactoryD::new()
                        'd'
                    ),
                'c'
            ),
        'b'
    )
    ->create();
```

Now I want to run database tests on `D` records but they are not persisted. Is there a workaround to persist them afterwards, is this intended behavior or is this a bug?

The problem lies here that deeper levels are called with "make" instead of "create": https://github.com/christophrumpel/laravel-factories-reloaded/blob/c889129c6505a44c5fdc3210b989849664cab795/src/BaseFactory.php#L129 because the `$creationType` parameter gets overwritten with "make"

**Comment by christophrumpel** [comment]
Hey, good question. Guess I never had that situation anymore. I'm now using L8 factories all the time and not this package anymore. Have you tried changing that part of the code? Do the other tests still pass?

**Comment by simonschaufi** [comment]
OK. I'm still on laravel 7 and make heavy use of your package. I was thinking about to change that peace of code but it's really not easy as you first need to make the nested models and then persist them with "saveMany". This just doesn't work recursively.

**Comment by christophrumpel** [comment]
@shaffe-fr Do you maybe have some to take a look here?

**Comment by shaffe-fr** [comment]
Hi @christophrumpel, I didn't had the time to look at it yet. But I'm on it.

**Comment by simonschaufi** [comment]
@shaffe-fr Do you have an idea how to solve this issue? I'm not sure if the new Laravel core factories support that feature but if it does, maybe it helps to solve this issue.

**Comment by shaffe-fr** [comment]
Hi @simonschaufi, as you were saying, a recursive function won't work for all types of relationship. Nested factories doesn't seem to work in  Laravel core factories. neither. The `Model::push()` method might help, but It won't work with all types of relationship (BelongsToMany if I remember well).

**Comment by simonschaufi** [comment]
Ok, then I need to find another solution for that, like persisting the outer object and then add the inner object to the outer one.
